In [1]:
import numpy as np

folder ="/home/marcnol/grey/ProcessedData_2024/Experiment_75_David_DNAFISH_HiM_HRKit_G1E_20240708/000/"

file = folder + "mask_3d/data/scan_002_mask0_000_ROI_converted_decon_ch01_3Dmasks_filtered_z_I.npy"

im = np.load(file)


In [5]:
print(im[10,1024:1124,1024:1124])
print(np.max(im))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
252
